parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType:  module
  ecmaFeatures:
    jsx:                          true
    experimentalObjectRestSpread: true

settings:
  react:
    version: 16.4

env:
  browser: true
  es6:     true

globals:
  global: true

extends:
  - eslint:recommended
  - plugin:react/recommended
